var menu ={
	main: [
		{url: "artsites", label: "Art >"},
		{url: "banking", label: "Banking >"},
		{url: "birds", label: "Birdwatching >"},
		{url: "entertainment", label: "Entertainment >"},
		{url: "family", label: "Family >"},
		{url: "games", label: "Games >"},
		{url: "genealogy", label: "Genealogy >"},
		{url: "holland", label: "Holland >"},
		{url: "news", label: "News >"},
		{url: "pictures", label: "Pictures >"},
		{url: "search", label: "Search and Reference >"},
		{url: "shopping", label: "Shopping >"},
		{url: "weather", label: "Weather >"},
	],
	artsites: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "http://www.cbc.ca/artspots", label: "CBC ArtSpots"},
		{url: "http://dailypainters.com/", label: "DailyPainters.com"},
		{url: "http://www.ebay.com/", label: "eBay"},
		{url: "http://art.shop.ebay.com/", label: "eBay - Art"},
		{url: "http://www.etsy.com/", label: "Etsy"},
		{url: "http://OmasFolkArt.etsy.com", label: "Etsy - Oma's Folk Art shop"},
		{url: "http://googleartproject.com", label: "Google Art Project"},
		{url: "http://london.kijiji.ca/f-buy-and-sell-art-collectibles-W0QQCatIdZ12", label: "Kijiji - London Art & Collectibles For Sale"},
		{url: "http://dir.yahoo.com/Arts/Artists/", label: "Yahoo! Arts  Artists"},
	],
	banking: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "https://www.myctfs.com/", label: "Canadian Tire Bank"},
		{url: "http://www.oaken.com/", label: "Oaken Banking"},
		{url: "http://www.paypal.com", label: "PayPal"},
		{url: "http://www.rbc.com/canada.html", label: "RBC Bank"},
		{url: "http://www.tangerine.ca/en/", label: "Tangerine"},
		{url: "http://www.td.com", label: "TDBank"},
	],
	birds: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "http://www.math.sunysb.edu/~tony/birds/", label: "Bird Songs of Birds of New York State"},
		{url: "http://www.birdwatchersdigest.com/", label: "Bird Watcher's Digest"},
		{url: "http://www.birdwatching.com/", label: "Birdwatching Dot Com"},
		{url: "http://www.birds.cornell.edu/AllAboutBirds", label: "Cornell Lab of Ornithology - All About Birds"},
		{url: "http://www.learnbirdsongs.com/", label: "Learn Bird Songs"},
	],
	entertainment: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "https://www.reddit.com/r/aww/", label: "Aww - Things that make you go AWW!"},
		{url: "http://www.comicssherpa.com/", label: "ComicsSherpa"},
		{url: "http://www.cowboycountrytv.com", label: "Cowboy Country TV"},
		{url: "http://www.cuteaddict.com/", label: "Cute Addict"},
		{url: "http://www.cuteoverload.com/", label: "Cute Overload"},
		{url: "http://gags.justforlaughs.com/", label: "Just For Laughs: Gags"},
		{url: "http://kittenwar.com/", label: "KittenWar"},
		{url: "http://www.theonion.com/", label: "The Onion"},
		{url: "file:///C:/Users/Public/Videos/Music/talent%20shows", label: "Talent Show Videos"},
		{url: "http://www.youtube.com", label: "YouTube"},
	],
	family: [
		{url: "main", label: "< Main Menu"},
		{url: "https://hharmsen.github.io", label: "Henry's Favourite Links"},
		{url: "https://frharmsen.github.io", label: "Rick's Favourite Links"},
	],
	games: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "https://frharmsen.github.io/computer/apps/games/DealOrNoDeal", label: "Deal Or No Deal"},
		{url: "https://frharmsen.github.io/computer/apps/games/PegSolitaire/PegSolitaire.html", label: "Peg Solitaire"},
		{url: "https://frharmsen.github.io/computer/apps/games/VideoPoker", label: "Video Poker"},
	],
	genealogy: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "http://boards.ancestry.com", label: "Ancestry Message Boards"},
		{url: "http://www.cbg.nl/", label: "Centrum voor Familiegeschiedenis"},
		{url: "https://familysearch.org/", label: "Family Search (Church of Latter Day Saints)"},
		{url: "http://www.geldersarchief.nl/", label: "Gelders Archief"},
		{url: "https://www.genealogieonline.nl/en/", label: "Genealogie Online"},
		{url: "http://genealogie.startpagina.nl/", label: "Genealogy Netherlands"},
		{url: "http://www.genealogytoday.com", label: "Genealogy Today"},
		{url: "http://www.geneanet.org", label: "GeneaNet"},
		{url: "http://www.geni.com/", label: "Geni.com"},
		{url: "http://www.mhsc.ca", label: "Mennonite Historical Society of Canada"},
		{url: "https://www.myheritage.com/", label: "MyHeritage"},
		{url: "http://www.regionaalarchiefzutphen.nl/", label: "Regionaal Archief Zutphen"},
		{url: "https://www.wiewaswie.nl/", label: "WieWasWie"},
		{url: "http://www.wikitree.com/", label: "WikiTree"},
	],
	holland: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "http://www.hettysite.nl/hetty", label: "Hetty's site"},
		{url: "http://www.mijnsvb.nl/", label: "My SVB"},
		{url: "http://www.koninklijkhuis.nl/", label: "Prince Klaus Memorial Website"},
		{url: "http://www.svb.nl/", label: "SVB"},
	],
	news: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "dutch", label: "News in Dutch >"},
		{url: "english", label: "News in English >"},
	],
	dutch: [
		{url: "news", label: "< News"},
		{url: "http://www.abyznewslinks.com/nethe.htm", label: "ABYZ News Links"},
		{url: "http://www.onlinenewspapers.com/netherla.htm", label: "All the World's Newspapers"},
		{url: "http://www.allyoucanread.com/holland-newspapers/", label: "All You Can Read"},
		{url: "http://www.contact.nl/", label: "Contact"},
		{url: "http://www.gelderlander.nl/", label: "De Gelderlander"},
		{url: "http://www.destentor.nl", label: "de Stentor"},
		{url: "http://news.google.nl", label: "Google News Nederland"},
		{url: "http://www.headlinespot.com/international/europe/netherlands.htm", label: "HeadlineSpot"},
		{url: "http://www.nu.nl", label: "NU"},
		{url: "http://dmoz.org/Regional/Europe/Netherlands/News_and_Media/Newspapers/", label: "Open Directory"},
		{url: "https://www.reddit.com/r/TheNetherlands", label: "Reddit - The Netherlands"},
		{url: "http://www.telegraaf.nl/", label: "Telegraaf"},
	],
	english: [
		{url: "news", label: "< News"},
		{url: "http://www.bbc.co.uk/worldservice/index.shtml", label: "BBC World Service"},
		{url: "http://www.cbc.ca/news", label: "CBC News"},
		{url: "http://www.counterpunch.org/", label: "CounterPunch"},
		{url: "http://www.ctvnews.ca/", label: "CTV News"},
		{url: "http://www.fraserinstitute.ca/", label: "Fraser Institute"},
		{url: "http://www.greaterfool.ca", label: "Garth Turner's Blog"},
		{url: "https://www.theglobeandmail.com/", label: "Globe and Mail"},
		{url: "http://goodtimes.ca", label: "Good Times"},
		{url: "http://news.google.ca", label: "Google News Canada"},
		{url: "http://www.janes.com/", label: "Jane's Information Group"},
		{url: "http://www.nationalpost.com/", label: "National Post"},
		{url: "http://www.ontariofarmer.com/sitepages/", label: "Ontario Farmer"},
		{url: "http://www.projectcensored.org/publications/2004", label: "Project Censored"},
		{url: "http://www.reddit.com/r/canada/", label: "Reddit - Canada"},
		{url: "http://www.reddit.com/r/worldnews/", label: "Reddit - World News"},
		{url: "http://www.theweeklynews.ca/elgincounty/", label: "St. Thomas/Elgin Weekly News"},
		{url: "http://www.stthomastoday.ca", label: "St. Thomas Today News"},
		{url: "http://www.lfpress.com/", label: "The London Free Press"},
		{url: "http://www.pbs.org/newshour/", label: "The Online NewsHour"},
		{url: "http://thestthomasblog.com/", label: "The St. Thomas Blog"},
		{url: "http://www.stthomastimesjournal.com/", label: "The St. Thomas Times-Journal"},
		{url: "http://www.washingtonpost.com/", label: "Washington Post"},
		{url: "https://ca.news.yahoo.com/europe/", label: "Yahoo News - Europe"},
	],
	pictures: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "flickr", label: "Flickr >"},
	],
	flickr: [
		{url: "pictures", label: "< Pictures"},
		{url: "http://www.flickr.com/groups/Barns", label: "Barns group"},
		{url: "http://www.flickr.com/groups/elgincounty/pool/", label: "Elgin County group"},
		{url: "https://www.flickr.com/explore", label: "Explore"},
		{url: "http://www.flickr.com/groups/79971663@N00/", label: "Graffit/Street Art group"},
		{url: "http://www.flickr.com/groups/ontarioruralruins", label: "Ontario Rural Ruins group"},
		{url: "http://www.flickr.com/groups/rural_ontario", label: "Rural Ontario group"},
		{url: "http://www.flickr.com/groups/squirrels", label: "Squirrels group"},
	],
	search: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "https://www.cia.gov/library/publications/the-world-factbook/", label: "CIA World Factbook"},
		{url: "http://www.google.ca", label: "Google (Canada)"},
		{url: "http://www.google.nl", label: "Google (The Netherlands)"},
		{url: "http://www.imdb.com", label: "Internet Motion-picture Database"},
		{url: "http://www.wikipedia.org", label: "Wikipedia"},
		{url: "http://www.yahoo.ca/", label: "Yahoo! Canada"},
	],
	shopping: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "http://www.brandsaver.ca/en_ca/", label: "BrandSaver"},
		{url: "http://www.canadianfreestuff.com/", label: "Canadian Free Stuff"},
		{url: "http://www.costco.ca/coupons.html", label: "CostCo Coupons"},
		{url: "http://flyerland.ca", label: "FlyerLand"},
		{url: "http://flyertown.ca", label: "FlyerTown"},
		{url: "http://ontario.foodland.ca/Home.aspx", label: "Foodland Weekly Flyer"},
		{url: "http://www.freshco.com/", label: "FreshCo"},
		{url: "http://www.gianttiger.com/", label: "Giant Tiger"},
		{url: "http://www.groceryalerts.ca/", label: "GroceryAlerts"},
		{url: "http://www.metro.ca/home.en.html", label: "Metro"},
		{url: "http://MrsJanuary.com/", label: "Mrs. January"},
		{url: "http://MyMilkCalendar.ca/Honda", label: "MyMilkCalendar"},
		{url: "http://pcplus.ca", label: "President's Choice PCPlus Programs"},
		{url: "https://www.realcanadiansuperstore.ca/", label: "Real Canadian Superstore Weekly"},
		{url: "http://www.redflagdeals.com/", label: "Red Flag Deals"},
		{url: "http://www.save.ca/", label: "Save.ca"},
		{url: "http://local.flyerservices.com/sdm/sdm/en?postalCode=N5p2m4", label: "Shoppers DrugMart"},
		{url: "http://SmartCanucks.ca/", label: "SmartCanucks"},
		{url: "http://smartsource.ca/", label: "SmartSource.ca"},
		{url: "http://www.stealthedeal.com/st-thomas", label: "StealTheDeal - St. Thomas"},
		{url: "http://www.frugalshopper.ca/", label: "The Frugal Shopper Canada"},
		{url: "http://www.walmart.ca/en", label: "Walmart"},
		{url: "http://WebSaver.ca/", label: "WebSaver.ca"},
	],
	weather: [
		{url: "main", label: "< Betty's Favourite Links"},
		{url: "aw", label: "Accuweather >"},
		{url: "ec", label: "Environment Canada >"},
		{url: "twn", label: "The Weather Network >"},
		{url: "http://www.mto.gov.on.ca/english/traveller/conditions/", label: "Winter Road Condition Reports"},
	],
	aw: [
		{url: "weather", label: "< Weather"},
		{url: "http://www.accuweather.com/en/ca/bancroft/k0l/weather-forecast/54942", label: "Bancroft"},
		{url: "http://www.accuweather.com/en/ca/ottawa/k1s/weather-forecast/55487", label: "Ottawa"},
		{url: "http://www.accuweather.com/en/ca/regina/s4r/weather-forecast/50335", label: "Regina"},
		{url: "http://www.accuweather.com/en/ca/st-thomas/n5p/weather-forecast/54997", label: "St. Thomas"},
		{url: "http://www.accuweather.com/en/us/zephyrhills-fl/33542/weather-forecast/337649", label: "Zephyrhills"},
	],
	ec: [
		{url: "weather", label: "< Weather"},
		{url: "http://weatheroffice.ec.gc.ca/city/pages/on-137_metric_e.html", label: "London"},
		{url: "http://weatheroffice.ec.gc.ca/city/pages/sk-24_metric_e.html", label: "Moose Jaw"},
		{url: "http://weatheroffice.ec.gc.ca/city/pages/on-98_metric_e.html", label: "St. Thomas"},
	],
	twn: [
		{url: "weather", label: "< Weather"},
		{url: "http://www.theweathernetwork.com/weather/cities/can/pages/CAON0041.htm", label: "Barry's Bay"},
		{url: "http://www.theweathernetwork.com/weather/canada/ontario/london", label: "London"},
		{url: "http://www.theweathernetwork.com/weather/canada/ontario/st-thomas", label: "St. Thomas"},
		{url: "https://weather.com/weather/tenday/l/Zephyrhills+FL+USFL0534:1:US", label: "Zephyrhills"},
	],
};
