TITLE="Betty's Collectable Sales - Betty's Sales - Personal Webpages - Betty's Favourite Links"

.PHONY: all

index.html: ../../../index.py index.csv
	python ../../../index.py index.csv index.html $(TITLE)

all:
	python ../../../ndex.py index.csv index.html $(TITLE)
	make -C bills all
